--- 
- hosts: debianserver
  become: yes
  tasks: 
  - name: testing by ping 
    ping:
  - name: install apache2 on debian 
    apt:
      name: "{{webpackondebian}}"
      state: present 
  - name: modyfing the index.html dynamically using template 
    template: 
      src: myindex.j2 
      dest: /var/www/html/index.html
    notify: restartserver

  handlers: 
  - name: restartserver
    service:
      name: apache2
      state: restarted
