--- 
- hosts: debianserver
  become: yes
  tasks: 
  - name: testing by ping 
    ping:
  - name: install apache2 on debian 
    apt:
      name: "{{webpackondebian}}"
      state: present 
  - include_tasks: dynfh.yml
    notify: restartserver

  handlers: 
  - name: restartserver
    service:
      name: apache2
      state: restarted
