--- 
- hosts: debianserver
  become: yes
  tasks: 
  - name: testing by ping 
    ping:
  - name: install apache2 on debian 
    apt:
      name: "{{webpackondebian}}"
      state: present 
    notify: stop server 
    
  - name: modyfing the index.html dynamically using template 
    template: 
      src: myindex.j2 
      dest: /var/www/html/index.html
    notify: start server


  handlers: 
  - name: start server
    service:
      name: apache2
      state: started
  - name: stop server
    service:
      name: apache2
      state: stopped
