--- 
- hosts: ubuntuserver
  become: yes
  tasks: 
  - name: ping - testing purpose
    ping:
  - include_tasks: filecreate.yml
  - include_tasks: foldercreate.yml
  - include_tasks: copy.yml 
  - name: downlod a jenkins.war file 
    get_url:
      url: https://updates.jenkins.io/download/war/2.510/jenkins.war
      dest: /home/maha/myfolder/jenkins.war
      force_basic_auth: yes
